# .tmuxconf   rev: 2020-04-29

#プレフィックスをCtrl-bからCtrl-tに変更
#unbind C-b
#set -g prefix C-t
#bind C-t send-prefix

#日本語対応
#setw -g utf8 on
#set -g status-utf8 on

# キーストロークのディレイを減らす
set -sg escape-time 1

# ウィンドウのインデックスを1から始める
set -g base-index 1

# ペインのインデックスを1から始める
setw -g pane-base-index 1

#キーバインドをvi風に
#set-window-option -g mode-keys vi

#256色対応
#set -g default-terminal "xterm-256color"
#set -g terminal-overrides "term:colors=256"
#set -g display-time 2000

# 異なるサイズの端末からアクセスした時にリサイズ
setw -g aggressive-resize on

#マウススクロール反映
#set-window-option -g mode-mouse on


# ウィンドウの移動
# Prefix(ここではCtrl+t)を連続入力することでウィンドウを移動させます。
bind C-t next-window


# ウィンドウを(ペインに)分割
# ＜Prefix＞＜v＞、＜Prefix＞＜h＞と入力するだけで分割できるようにします。
#bind v split-window -v
#bind h split-window -h
unbind %
bind | split-window -h
unbind '"'
bind '-' split-window -v

# ペインのサイズ変更をvim風にする
# ＜Prefix＞＜Ctrl + { h | i | j | k }＞
# ＜Ctrl + { h | i | j | k }＞は連続して入力可能。
# 1回押すごとに5行(列)境界を移動させる。
bind -r C-h resize-pane -L 5
bind -r C-l resize-pane -R 5
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5


# ペインの移動1(Vim風にする)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R


# ペインの移動2
# Shift + 上下左右でペインを移動できるようにする。(＜Prefix＞不要)
# 行頭に"bind -n"をつけるとPrefixが不要になる。
bind -n S-left select-pane -L
bind -n S-down select-pane -D
bind -n S-up select-pane -U
bind -n S-right select-pane -R


# キーストロークのディレイを減らす
set -sg escape-time 1


# Vimのキーバインドでペインを移動する
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

# Vimのキーバインドでペインをリサイズする
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

## マウス操作を有効にする
# 2.0 or below
#setw -g mode-mouse on
#set -g mouse-select-pane on
#set -g mouse-resize-pane on
#set -g mouse-select-window on
# 2.1 or later
set-option -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"

# 256色端末を使用する
set -g default-terminal "screen-256color"

## ステータスバーの色を設定する
#set -g status-fg white
#set -g status-bg black
set -g status-fg white
set -g status-bg blue

# 2020/04/29
# 
## ウィンドウリストの色を設定する
#setw -g window-status-fg blue
#setw -g window-status-bg default
#setw -g window-status-attr dim
#
## アクティブなウィンドウを目立たせる
##setw -g window-status-current-fg white
##setw -g window-status-current-bg red
#setw -g window-status-current-fg black
#setw -g window-status-current-bg white
#setw -g window-status-current-attr bright
#
## ペインボーダーの色を設定する
#set -g pane-border-fg green
#set -g pane-border-bg black
## アクティブなペインを目立たせる
#set -g pane-active-border-fg white
#set -g pane-active-border-bg yellow
#
## コマンドラインの色を設定する
#set -g message-fg white
#set -g message-bg black
#set -g message-attr bright
#
## 2015/05/14
## Use vim keybindings in copy mode
#setw -g mode-keys vi
#
## Setup 'v' to begin selection as in Vim
#bind-key -t vi-copy v begin-selection
#bind-key -t vi-copy y copy-pipe "reattach-to-user-namespace pbcopy"
#
## Update default binding of `Enter` to also use copy-pipe
#unbind -t vi-copy Enter
#bind-key -t vi-copy Enter copy-pipe "reattach-to-user-namespace pbcopy"



